### ISSUE TITLE
Firefox has a gap between tracks

### ISSUE THREAD

**Issue by expesh** [regosen/Gapless-5#40]
**Describe the bug**
There is an audible gap when transitioning between 2 tracks on firefox. The same gap isn't audible on latest chromium browsers. I used .flac files while encountering this bug.

Firefox version: Linux 104.0.2 64bit
Chromium browser version: Linux 104.0.5112.102 64bit (Brave version 1.42.97)

In my testing, I started the playback of track 1 and seeked near to the end of it. I then waited for the next track to start to hear the transition between the tracks. Here's my sample code I was using:
```
const player = new Gapless5({
  tracks: [
    // gives a .flac file as a response
    `http://localhost:7777/musicfile?id=17179869343`,
    `http://localhost:7777/musicfile?id=17179869344`,
  ],
  loadLimit: 2,
  volume: 0.3,
  logLevel: LogLevel.Debug,
});

player.play();

// seek near the end of the first track so that I can hear the transition quicker
setTimeout(() => {
  player.setPosition(120 * 1000);
}, 1000);
```

**Debug output**
```
Setting starting track to 0 [gapless5.js:441:8](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.3.16/node_modules/@regosen/gapless-5/gapless5.js)
Loadable indices: [0,1] [gapless5.js:619:8](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.3.16/node_modules/@regosen/gapless-5/gapless5.js)
Loading track 0: http://localhost:7777/musicfile?id=17179869343 [gapless5.js:631:14](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.3.16/node_modules/@regosen/gapless-5/gapless5.js)
Loading track 1: http://localhost:7777/musicfile?id=17179869344 [gapless5.js:631:14](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.3.16/node_modules/@regosen/gapless-5/gapless5.js)
Loading http://localhost:7777/musicfile?id=17179869343 [gapless5.js:260:10](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.3.16/node_modules/@regosen/gapless-5/gapless5.js)
Playing HTML5 Audio: http://localhost:7777/musicfile?id=17179869343 [gapless5.js:233:14](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.3.16/node_modules/@regosen/gapless-5/gapless5.js)
onEnded() will be called in 128.29 sec [gapless5.js:185:8](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.3.16/node_modules/@regosen/gapless-5/gapless5.js)
Switching from HTML5 to WebAudio: http://localhost:7777/musicfile?id=17179869343 [gapless5.js:128:10](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.3.16/node_modules/@regosen/gapless-5/gapless5.js)
Playing WebAudio: http://localhost:7777/musicfile?id=17179869343 [gapless5.js:203:14](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.3.16/node_modules/@regosen/gapless-5/gapless5.js)
onEnded() will be called in 127.82 sec [gapless5.js:185:8](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.3.16/node_modules/@regosen/gapless-5/gapless5.js)
Stopping: http://localhost:7777/musicfile?id=17179869343 [gapless5.js:158:8](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.3.16/node_modules/@regosen/gapless-5/gapless5.js)
Playing WebAudio: http://localhost:7777/musicfile?id=17179869343 [gapless5.js:203:14](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.3.16/node_modules/@regosen/gapless-5/gapless5.js)
onEnded() will be called in 8.27 sec [gapless5.js:185:8](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.3.16/node_modules/@regosen/gapless-5/gapless5.js)
onEnded() will be called in 128.27 sec [gapless5.js:185:8](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.3.16/node_modules/@regosen/gapless-5/gapless5.js)
Stopping: http://localhost:7777/musicfile?id=17179869343 [gapless5.js:158:8](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.3.16/node_modules/@regosen/gapless-5/gapless5.js)
Setting track number to 1 [gapless5.js:463:8](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.3.16/node_modules/@regosen/gapless-5/gapless5.js)
Loadable indices: [1,2] [gapless5.js:619:8](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.3.16/node_modules/@regosen/gapless-5/gapless5.js)
Stopping: http://localhost:7777/musicfile?id=17179869343 [gapless5.js:158:8](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.3.16/node_modules/@regosen/gapless-5/gapless5.js)
Unloaded track 0: http://localhost:7777/musicfile?id=17179869343 [gapless5.js:635:14](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.3.16/node_modules/@regosen/gapless-5/gapless5.js)
Playing WebAudio: http://localhost:7777/musicfile?id=17179869344 [gapless5.js:203:14](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.3.16/node_modules/@regosen/gapless-5/gapless5.js)
onEnded() will be called in 201.27 sec
```

**Comment by regosen** [comment]
Thanks for the report.  Gapless 1.4.0 has just been released with a possible fix for this.  Please let me know if you still encounter any issues.

(You can also customize the crossfade and lookahead for transitions between tracks, have a look at the [readme](https://github.com/regosen/Gapless-5/blob/main/README.md) and search for "crossfade")

**Comment by expesh** [comment]
The new version doesn't have a same type of gap as the previous version, but now the new track seems to actually start playing before the previous track finishes. It actually sounds to my ears a lot worse than the previous version, and it obviously still isn't gapless. Also, the current version has this same bug both in Firefox and Chrome.

Am I supposed to change the value of `crossfadeShape` to make gapless playback work? I tried both `EqualPower` and `NONE` and they sound identical. Also, shouldn't the `CrossfadeShape` type be exported from the package? I don't see it being exported anywhere in the new version and so I had to change the numbers manually (look up the number in the gapless.js code and set it to that).

Here's the debug logs:

```
Setting starting track to 0 [gapless5.js:535:8](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.4.0/node_modules/@regosen/gapless-5/gapless5.js)
Loadable indices: [0,1] [gapless5.js:748:8](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.4.0/node_modules/@regosen/gapless-5/gapless5.js)
Loading track 0: http://localhost:7777/musicfile?segment=01 [gapless5.js:760:14](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.4.0/node_modules/@regosen/gapless-5/gapless5.js)
Loading track 1: http://localhost:7777/musicfile?segment=02 [gapless5.js:760:14](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.4.0/node_modules/@regosen/gapless-5/gapless5.js)
Loading http://localhost:7777/musicfile?segment=01 [gapless5.js:343:10](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.4.0/node_modules/@regosen/gapless-5/gapless5.js)
Playing HTML5 Audio: http://localhost:7777/musicfile?segment=01 at 0.00 sec [gapless5.js:312:14](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.4.0/node_modules/@regosen/gapless-5/gapless5.js)
onEnded() will be called on http://localhost:7777/musicfile?segment=01 in 128.24 sec [gapless5.js:247:10](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.4.0/node_modules/@regosen/gapless-5/gapless5.js)
Switching from HTML5 to WebAudio: http://localhost:7777/musicfile?segment=01 [gapless5.js:185:10](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.4.0/node_modules/@regosen/gapless-5/gapless5.js)
Playing WebAudio: http://localhost:7777/musicfile?segment=01 at 0.47 sec [gapless5.js:288:14](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.4.0/node_modules/@regosen/gapless-5/gapless5.js)
onEnded() will be called on http://localhost:7777/musicfile?segment=01 in 127.74 sec [gapless5.js:247:10](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.4.0/node_modules/@regosen/gapless-5/gapless5.js)
Stopping: http://localhost:7777/musicfile?segment=01 [gapless5.js:216:8](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.4.0/node_modules/@regosen/gapless-5/gapless5.js)
Playing WebAudio: http://localhost:7777/musicfile?segment=01 at 120.00 sec [gapless5.js:288:14](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.4.0/node_modules/@regosen/gapless-5/gapless5.js)
onEnded() will be called on http://localhost:7777/musicfile?segment=01 in 8.21 sec [gapless5.js:247:10](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.4.0/node_modules/@regosen/gapless-5/gapless5.js)
Stopping: http://localhost:7777/musicfile?segment=02 [gapless5.js:216:8](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.4.0/node_modules/@regosen/gapless-5/gapless5.js)
Setting track number to 1 [gapless5.js:573:8](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.4.0/node_modules/@regosen/gapless-5/gapless5.js)
Loadable indices: [1,2,0] [gapless5.js:748:8](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.4.0/node_modules/@regosen/gapless-5/gapless5.js)
Playing WebAudio: http://localhost:7777/musicfile?segment=02 at 0.00 sec [gapless5.js:288:14](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.4.0/node_modules/@regosen/gapless-5/gapless5.js)
onEnded() will be called on http://localhost:7777/musicfile?segment=02 in 201.27 sec [gapless5.js:247:10](http://localhost:5173/node_modules/.pnpm/@regosen+gapless-5@1.4.0/node_modules/@regosen/gapless-5/gapless5.js)
Stopping: http://localhost:7777/musicfile?segment=01
```

**Comment by regosen** [comment]
Thanks so much for the quick feedback!  My apologies, I forgot to export `CrossfadeShape`.  I'm also restoring the default behavior- I tried to add a default crossfade under the hood as a "best-fit" but now I realize it should be opt-in.

With 1.4.1 it should sound like before (without the track overlap).  I also simplified the options.  Now all you have to do to experiment with the gaps is to set the `crossfade` option.  Try setting it to 25 (it's on milliseconds) and adjust as needed.

**Comment by expesh** [comment]
Thanks for the update. I was hoping that there would be no need to manually play with any delay numbers, especially in the case of FLAC files since they don't have any padding samples like AAC so gapless playback should be easily doable. I know gapless playback is doable with `AudioContext` at least when loading HLS segments but I guess it's not possible when passing in full audio files like with this library? I just had the impression from this library that gapless playback should work out of the box without any manual case-by-case delay adjustments; please do correct me if I'm wrong and feel free to close the issue if that is not the case.

**Comment by regosen** [comment]
Hi, I was hoping to come up with a white glove approach as well, but there are too many variables at play because different browsers introduce different latency (and I found that AudioContext.baseLatency doesn’t cover all of it).  This library plays the tracks as separate audio sources instead of reading/writing them into a single stream.

That being said, if you’re using flac try a small number like 6 ms for the crossfade parameter, that seemed to work well on another project that uses flac.

**Comment by expesh** [comment]
Fair enough. I'll close the issue then, since this seems to be an implementation decision rather than a bug with the current implementation.

Just out of curiosity, have you looked into trying to implement playback using just a single buffer/stream, using a `SourceBuffer`? If using a single `SourceBuffer` for all of the tracks it's possible to have completely gapless playback on all browsers without any delay hacks. But I'm not sure if `SourceBuffer`s work that well when loading full audio files instead of segments like with HLS.

**Comment by regosen** [comment]
That's a good question, I'll have to dive into this more deeply sometime.  Some early research indicates that AudioBufferSourceNode is intended for short audio assets in memory, and we'd hit memory limits by continually adding to the buffer.

That being said, MediaElementAudioSourceNode seems more promising...
